version: '3'
networks:
    maestro-net:
      driver: bridge
services: 
  maestro-broker:
    build: maestro-broker
    networks: 
      - maestro-net
    ports:
      - "18161:8161"
      # Usually it's not needed to expose MQTT port
      # - "18883:1883"
  maestro-sut:
    build: maestro-suts/apache-activemq
    networks: 
      - maestro-net
    ports:
      - "48161:8161"
      - "45672:5672"
      - "41616:61616"
  maestro-receiver:
    build:
      context: maestro-worker/maestro-receiver
    ports:
      - "28000:8000"
    volumes:
      - ${HOME}/tmp/maestro:/maestro
    networks: 
      - maestro-net
    depends_on:
      # - maestro-worker
      - maestro-broker
      - maestro-sut
  maestro-sender:
    build: maestro-worker/maestro-sender
    ports:
      - "38000:8000"
    volumes:
      - ${HOME}/tmp/maestro:/maestro
    networks: 
      - maestro-net
    depends_on:
      # - maestro-worker
      - maestro-broker
      - maestro-sut
  maestro-client:
    build: maestro-client
    volumes:
      - ${HOME}/tmp/maestro:/maestro
    networks: 
      - maestro-net
    ports:
      - "8000:8000"
    depends_on:
      - maestro-sender
      - maestro-receiver
  