apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-sender
spec:
  replicas: 0
  selector:
    matchLabels:
      component: sender
      app: maestro
  template:
    metadata:
      labels:
        component: sender
        app: maestro
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - maestroperf
      containers:
        - name: sender
          image: maestroperf/maestro-sender:1.3.0
          env:
            - name: MAESTRO_BROKER
              value: mqtt://broker.svc
          volumeMounts:
            - mountPath: /maestro/sender/logs
              name: logging-volume
      volumes:
        - name: logging-volume
          emptyDir: {}
