apiVersion: v1
kind: Service
metadata:
  name: reports-external
spec:
  type: NodePort
  ports:
    - name: http
      port: 6500
      nodePort: 30001
  selector:
    app: maestro
    component: reports

