apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-reports
spec:
  replicas: 0
  selector:
    matchLabels:
      component: reports
      app: maestro
  template:
    metadata:
      labels:
        component: reports
        app: maestro
    spec:
      strategy:
        type: Recreate
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - maestroperf
      initContainers:
        - name: copyconfig
          image: centos:7
#          command:
#            - /bin/bash
#            - -c
#            - cp /config/* /opt/maestro/maestro-worker/config/ && echo maestro.worker.host=$HOSTNAME >> /opt/maestro/maestro-worker/config/maestro-worker.properties
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config
              mountPath: /config
            - mountPath: /opt/maestro/maestro-reports-tool/config
              name: config-store
      containers:
        - name: maestro-reports
          image: maestroperf/maestro-reports:1.5.0-SNAPSHOT
          env:
            - name: MAESTRO_BROKER
              value: mqtt://broker
          ports:
            - name: http
              containerPort: 6500
          volumeMounts:
            - mountPath: /opt/maestro/maestro-reports/config
              name: config-store
            - mountPath: /maestro
              name: data
      volumes:
        - name: data
          emptyDir: {}
        - name: config-store
          emptyDir: {}
        - name: config
          configMap:
            name: reports-config
