version: '3.4'
networks:
    cluster:
      driver: bridge
    test:
          driver: bridge
services:
  broker:
    build: broker
    networks:
      - cluster
    ports:
      - "18161:8161"
      - "1884:1883"