version: '3.4'
networks:
    cluster:
      driver: bridge
    test:
          driver: bridge
services:
  broker:
    build: broker
    networks:
      - cluster
    ports:
      - "18161:8161"
      - "1884:1883"
  sut:
    build: suts/apache-artemis
# Comment the line above and uncomment the 4 lines below
# to use QPid Dispatch as the SUT
#    build:
#      context: suts/qpid-dispatch
#      args:
#        - QPID_DISPATCH_VERSION=1.4.0
#        - QPID_PROTON_VERSION=0.26.0
#    image: docker.io/rabbitmq:3-management
    networks:
      - test
    ports:
      - "5672:5672"
      - "8161:8161"
      - "61613:61613"
      - "61616:61616"
# Include this one for RabbitMQ management interface
#      - "15672:15672"